classdef meta_data_class < handle
    properties
        track_ids = []
        x_size = []
        y_size = []
        classIDs = []
        augmented = []
        fileIDs = []
    end
    methods
        function copy_add(obj,inds)
            obj.track_ids = [ obj.track_ids,...
                            obj.track_ids(inds)];
            obj.x_size = [obj.x_size,...
                          obj.x_size(inds)];
            obj.y_size = [obj.y_size,...
                          obj.y_size(inds)];
            obj.classIDs = [obj.classIDs,...
                            obj.classIDs(inds)];
            obj.augmented = [obj.augmented, ...
                            obj.augmented(inds)];
            obj.fileIDs  = [obj.fileIDs, ...
                            obj.fileIDs(inds)];
        end
        
        function matarr = make_mat(obj)
            matarr  = [obj.track_ids;...
                       obj.x_size;...
                       obj.y_size;...
                       obj.classIDs;...
                       obj.augmented;...
                       obj.fileIDs];
        end
        function load_meta(obj,meat)
            obj.track_ids = [obj.track_ids,...
                            meat(1,:)];
            obj.x_size = [obj.x_size,...
                          meat(2,:)];
            obj.y_size = [obj.y_size,...
                          meat(3,:)];
            obj.classIDs = [obj.classIDs,...
                            meat(4,:)];
            obj.augmented = [obj.augmented, ...
                            meat(5,:)];
            obj.fileIDs  = [obj.fileIDs, ...
                            meat(6,:)];
        end
        function add_meta_data(obj,track_id,x_size,...
                y_size,class_ID,augmented,track_length,fileID)
            obj.track_ids = [obj.track_ids,...
                              track_id];
            obj.x_size = [obj.x_size,...
                          x_size];
            obj.y_size = [obj.y_size,...
                          y_size];
            obj.classIDs = [obj.classIDs,...
                            class_ID];
            obj.augmented = [obj.augmented, ...
                            augmented];
            obj.fileIDs  = [obj.fileIDs, ...
                            ones(1,track_length)*fileID];
        end
    end
    methods (Static)
        function obj = init_meta_data
            obj.track_ids = [];
            obj.x_size = [];
            obj.y_size = [];
        end
    end
end
