function frames=my_medfilt2(frame,stride)

% Applies the median filter according to the stride
frames=frame;

max_x=size(frame,1);
max_y=size(frame,2);

if (stride==3)
    for x=1:stride:max_x
        for y=1:stride:max_y
            med_value=mean(mean(frame(max(x-1,1):min(x+1,max_x),max(y-1,1):min(y+1,max_y),:),1),2);
            frames(x,y,med_value>0.5)=1;
            frames(max(x-1,1):min(x+1,max_x),max(y-1,1):min(y+1,max_y),med_value<=0.5)=0;
        end
    end
end

if (stride==1)
    frames(1,1)=(frame(1,1)+frame(1,2)+frame(2,1)+frame(2,2)>=2);
    frames(1,end)=(frame(1,end)+frame(1,end-1)+frame(2,end)+frame(2,end-1)>=2);
    frames(end,1)=(frame(end,1)+frame(end-1,1)+frame(end,2)+frame(end-1,2)>=2);
    frames(end,end)=(frame(end,end)+frame(end,end-1)+frame(end-1,end)+frame(end-1,end-1)>=2);
    frames(1,2:end-1)=(frame(1,1:end-2)+...
        frame(2,1:end-2)+...
        frame(1,2:end-1)+...
        frame(2,2:end-1)+...
        frame(1,3:end)+...
        frame(2,3:end)>=3);
    frames(end,2:end-1)=(frame(end-1,1:end-2)+...
        frame(end,1:end-2)+...
        frame(end-1,2:end-1)+...
        frame(end,2:end-1)+...
        frame(end-1,3:end)+...
        frame(end,3:end)>=3);
    frames(2:end-1,1)=(frame(1:end-2,1)+...
        frame(1:end-2,2)+...
        frame(2:end-1,1)+...
        frame(2:end-1,2)+...
        frame(3:end,1)+...
        frame(3:end,2)>=3);
    frames(2:end-1,end)=(frame(1:end-2,end-1)+...
        frame(1:end-2,end)+...
        frame(2:end-1,end-1)+...
        frame(2:end-1,end)+...
        frame(3:end,end-1)+...
        frame(3:end,end)>=3);
    frames(2:end-1,2:end-1)=(frame(1:end-2,1:end-2)+...
        frame(2:end-1,1:end-2)+...
        frame(3:end,1:end-2)+...
        frame(1:end-2,2:end-1)+...
        frame(2:end-1,2:end-1)+...
        frame(3:end,2:end-1)+...
        frame(1:end-2,3:end)+...
        frame(2:end-1,3:end)+...
        frame(3:end,3:end)>=5);
end
end
